const C=document.getElementById('content'),T=document.getElementById('title');const nav=document.querySelectorAll('nav button');
const params=new URLSearchParams(location.search);
const loggedRole=params.get("role")||"admin";
const loggedName=params.get("name")||"Administrator";
document.querySelector(".profile b").textContent=loggedName;
document.querySelector(".profile small").textContent=
  loggedRole==="wakakur"||loggedRole==="wakasis"||loggedRole==="wakahumasy"||loggedRole==="wakasarpras"
  ? "Wakil Kepala" : (loggedRole==="admin" ? "Admin / Tata Usaha" : loggedRole.toUpperCase());

const pages={
 dashboard:['Dashboard Admin',dashboard],identitas:['Hal 1 — Lembar Identitas Siswa',identitas],kelas10:['Hal 2 — Laporan Hasil Belajar Kelas X',()=>hasil('X')],kelas11:['Hal 3 — Laporan Hasil Belajar Kelas XI',()=>hasil('XI')],kelas12:['Hal 4 — Laporan Hasil Belajar Kelas XII',()=>hasil('XII')],lampiran:['Hal 5 — Ijazah & Sertifikat TKA',lampiran],password:['Hal 6 — Kelola Sandi Setiap Dashboard',password]};
function go(k){T.textContent=pages[k][0];C.innerHTML=pages[k][1]();nav.forEach(x=>x.classList.toggle('active',x.dataset.p===k));document.getElementById('side').classList.remove('open');}
nav.forEach(x=>x.onclick=()=>go(x.dataset.p));document.getElementById('hamb').onclick=()=>document.getElementById('side').classList.toggle('open');
function dashboard(){return `<div class=head><div><span class=eyebrow>ADMINISTRASI TATA USAHA</span><h2>Dashboard Admin</h2><p class=sub>Pusat pengelolaan Buku Induk Siswa.</p></div></div><div class=stats><div class=stat><small>TOTAL SISWA</small><strong>—</strong></div><div class=stat><small>KELAS X</small><strong>—</strong></div><div class=stat><small>KELAS XI</small><strong>—</strong></div><div class=stat><small>KELAS XII</small><strong>—</strong></div></div><div class=two><div class=card><h3>Akses Cepat</h3><div class=quick><button onclick="go('identitas')">01 · Identitas Siswa</button><button onclick="go('kelas10')">02 · Hasil Belajar X</button><button onclick="go('kelas11')">03 · Hasil Belajar XI</button><button onclick="go('kelas12')">04 · Hasil Belajar XII</button><button onclick="go('lampiran')">05 · Ijazah & TKA</button><button onclick="go('password')">06 · Kelola Sandi</button></div></div><div class=card><h3>Status Sistem</h3><div class=notice>● Sistem aktif. Jam real time mengikuti perangkat.</div><b>Role:</b> Admin / TU<br><br><b>Format:</b> Folio / F4</div></div>`}
function identitas(){return `<div class=head><div><span class=eyebrow>HALAMAN 1</span><h2>Lembar Identitas Siswa + Foto</h2><p class=sub>Nama, nama panggilan, identitas kependudukan dan data pokok.</p></div><div class=actions><button class=btn>💾 Simpan</button><button class="btn green" onclick="printDoc('Lembar Identitas Siswa','id')">🖨 Print F4</button></div></div><div class=card><div class=student><div><div class=photo>FOTO SISWA<br>3 × 4</div><button class=btn style="margin-top:8px">＋ Upload Foto</button></div><div class=formgrid>${fields([['NIS','Nomor Induk Siswa'],['NISN','NISN'],['Nama Lengkap','Nama lengkap siswa'],['Nama Panggilan','Nama panggilan'],['Tempat Lahir','Kabupaten/Kota'],['Tanggal Lahir',''],['Jenis Kelamin','Pilih'],['NIK','Nomor Induk Kependudukan'],['Agama','Pilih agama'],['No. KK','Nomor Kartu Keluarga'],['Anak Ke','Contoh: 2'],['Status Dalam Keluarga','Anak kandung / lainnya']])}<div class=field style="grid-column:1/-1"><label>Alamat Lengkap</label><textarea></textarea></div></div></div></div>`}
function fields(a){return a.map(x=>`<div class=field><label>${x[0]}</label><input placeholder="${x[1]}"></div>`).join('')}
function hasil(k){return `<div class=head><div><span class=eyebrow>HALAMAN ${k==='X'?2:k==='XI'?3:4}</span><h2>Laporan Hasil Belajar Kelas ${k}</h2><p class=sub>Semester 1 — 2 · Cetak Folio / F4.</p></div><div class=actions><button class="btn gold" onclick="printDoc('Laporan Hasil Belajar Kelas ${k}','nilai')">🖨 Print F4</button><button class=btn>⇧ Import</button><button class=btn>⇩ Export</button></div></div><div class=card><div class=formgrid><div class=field><label>Pilih Siswa</label><select><option>— Pilih siswa —</option></select></div><div class=field><label>Tahun Pelajaran</label><input placeholder="2026 / 2027"></div></div><div class=semester><h3>Semester 1</h3></div>${nilai()}<div class=semester><h3>Semester 2</h3></div>${nilai()}</div>`}
function nilai(){return `<table><thead><tr><th>No</th><th>Mata Pelajaran</th><th>Nilai</th><th>Predikat</th><th>Catatan</th></tr></thead><tbody>${['Pendidikan Agama','Pendidikan Pancasila','Bahasa Indonesia','Matematika','Bahasa Inggris','Sejarah','Informatika','PJOK'].map((x,i)=>`<tr><td>${i+1}</td><td>${x}</td><td><input type=number min=0 max=100></td><td><input></td><td><input></td></tr>`).join('')}</tbody></table>`}
function lampiran(){return `<div class=head><div><span class=eyebrow>HALAMAN 5</span><h2>Lampiran Ijazah & Sertifikat TKA</h2><p class=sub>Dokumen kelulusan dan sertifikat peserta didik.</p></div><button class="btn green" onclick="printDoc('Lampiran Ijazah dan Sertifikat TKA','lampiran')">🖨 Print F4</button></div><div class=card><div class=formgrid>${fields([['Pilih Siswa','— Pilih siswa —'],['Jenis Dokumen','Ijazah / Sertifikat TKA'],['Nomor Dokumen','Nomor ijazah / sertifikat'],['Tanggal Dokumen','']])}</div><br><div class=drop>📎<br><b>Upload dokumen</b><br>PDF / JPG / PNG</div></div>`}
function password(){return `<div class=head><div><span class=eyebrow>HALAMAN 6</span><h2>Kelola Sandi Setiap Dashboard</h2><p class=sub>Admin dapat mengelola kredensial tiap dashboard.</p></div><button class="btn green" onclick="alert('Perubahan ditandai untuk disimpan. Backend keamanan dapat dihubungkan berikutnya.')">💾 Simpan</button></div><div class=card><div class=notice>Untuk produksi, password wajib disimpan dengan hashing di backend, bukan di JavaScript.</div>${['ADMIN / TU','KEPALA SEKOLAH','WAKA KURIKULUM','WAKA KESISWAAN','WAKA HUMAS','WAKA SARPRAS','KOPSIS','LABKOM','PERPUSTAKAAN'].map(x=>`<div class=passrow><b>${x}</b><input placeholder="Nama akun"><input type=password placeholder="Sandi baru"><button class=btn>Ubah</button></div>`).join('')}</div>`}
function printDoc(t,type){document.getElementById('ptitle').textContent=t;let p=document.getElementById('paper');if(type==='id')p.innerHTML='<h3>LEMBAR IDENTITAS PESERTA DIDIK</h3><table><tr><td>Nama Lengkap</td><td></td></tr><tr><td>Nama Panggilan</td><td></td></tr><tr><td>NIS / NISN</td><td></td></tr><tr><td>Tempat, Tanggal Lahir</td><td></td></tr><tr><td>Jenis Kelamin</td><td></td></tr><tr><td>Alamat</td><td></td></tr></table>';else if(type==='nilai')p.innerHTML='<h3>'+t.toUpperCase()+'</h3><p>Nama Siswa: ................................ &nbsp; Tahun Pelajaran: ................</p><table><tr><th>No</th><th>Mata Pelajaran</th><th>Semester 1</th><th>Semester 2</th></tr>'+['Pendidikan Agama','Pendidikan Pancasila','Bahasa Indonesia','Matematika','Bahasa Inggris','Sejarah','Informatika','PJOK'].map((x,i)=>`<tr><td>${i+1}</td><td>${x}</td><td></td><td></td></tr>`).join('')+'</table>';else p.innerHTML='<h3>'+t.toUpperCase()+'</h3><table><tr><th>No</th><th>Jenis Dokumen</th><th>Nomor</th><th>Tanggal</th><th>Keterangan</th></tr><tr><td>1</td><td>Ijazah</td><td></td><td></td><td></td></tr><tr><td>2</td><td>Sertifikat TKA</td><td></td><td></td><td></td></tr></table>';document.getElementById('modal').classList.add('show')}
function closePrint(){document.getElementById('modal').classList.remove('show')}
function tick(){let d=new Date();document.getElementById('clock').textContent=d.toLocaleTimeString('id-ID',{hour12:false});document.getElementById('date').textContent=d.toLocaleDateString('id-ID',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}setInterval(tick,1000);tick();go('dashboard');
